# Generated by Django 4.1.5 on 2023-02-06 07:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        editable=False, unique=True, verbose_name="Payriff order ID"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Payriff session ID",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=8, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "id_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Passport number / ID number",
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "order_ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.orderticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_registration_active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255, null=True)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("price_text", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        choices=[("student", "Student"), ("other", "Other")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_limited", models.BooleanField(default=False)),
                (
                    "no_available",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Number of available tickets",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[("online", "Online"), ("in-person", "In-person")],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("includes_dinner", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=50)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderticket",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ticket"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ticket"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="MealPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                (
                    "special_request",
                    models.TextField(
                        blank=True,
                        help_text="E.g halal, kosher, vegetarian etc.",
                        null=True,
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.participant",
                    ),
                ),
            ],
        ),
    ]
