# Generated by Django 4.1.5 on 2023-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ticket",
        ),
        migrations.AddField(
            model_name="order",
            name="tickets",
            field=models.ManyToManyField(through="core.OrderTicket", to="core.ticket"),
        ),
    ]
