# Generated by Django 4.1.6 on 2023-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(unique=True, verbose_name="Payriff order ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="session_id",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Payriff session ID"
            ),
        ),
    ]
