# Generated by Django 4.1.5 on 2023-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_locality_ticket_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="includes_dinner",
            field=models.BooleanField(default=False),
        ),
    ]
