# Generated by Django 4.1.5 on 2023-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_registrationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_id",
            field=models.CharField(
                editable=False,
                max_length=50,
                null=True,
                verbose_name="Payriff session ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(editable=False, verbose_name="Payriff order ID"),
        ),
    ]
