# Generated by Django 4.1.6 on 2023-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Complete"),
                    ("CANCELED", "Cancelled"),
                    ("DECLINED", "Declined"),
                    ("REFUNDED", "Refunded"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
