# Generated by Django 4.1.5 on 2023-02-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_mealpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.order"
            ),
        ),
        migrations.AlterField(
            model_name="studentparticipant",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.participant"
            ),
        ),
    ]
