# Generated by Django 4.1.5 on 2023-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_session_id_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(
                editable=False, unique=True, verbose_name="Payriff order ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="session_id",
            field=models.CharField(
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Payriff session ID",
            ),
        ),
    ]
