# Generated by Django 4.1.5 on 2023-01-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_order_order_id_alter_order_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="datetime",
            new_name="created",
        ),
        migrations.AddField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
