# Generated by Django 4.1.5 on 2023-02-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_participant_order_and_more"),
    ]

    operations = []
