# Generated by Django 4.1.6 on 2023-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Payriff order ID"
            ),
        ),
    ]
