# Generated by Django 4.1.5 on 2023-01-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_ticket_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="active",
            new_name="is_active",
        ),
    ]
