# Generated by Django 4.1.6 on 2023-02-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.ticket"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="order_ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.orderticket"
            ),
        ),
    ]
