# Generated by Django 4.1.6 on 2023-02-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_order_user_alter_orderticket_order_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("order_id", "session_id")},
        ),
    ]
