# Generated by Django 4.1.5 on 2023-01-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_active_ticket_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="type",
        ),
        migrations.DeleteModel(
            name="TicketType",
        ),
    ]
