# Generated by Django 4.1.6 on 2023-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_order_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Payriff order ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="session_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Payriff session ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("CANCELED", "Canceled"),
                    ("DECLINED", "Declined"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=12,
                null=True,
            ),
        ),
    ]
