# Generated by Django 4.1.5 on 2023-01-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_ticket_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="summary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
