# Generated by Django 4.1.5 on 2023-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_ticket_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_limited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="no_available",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of available tickets"
            ),
        ),
    ]
