# Generated by Django 4.1.5 on 2023-02-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ticket_is_limited_ticket_no_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price_text",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
