# Generated by Django 4.1.5 on 2023-02-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_ticket_price_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="locality",
            field=models.CharField(default="online", max_length=20),
        ),
    ]
