# Generated by Django 4.1.6 on 2023-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_freeregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="institution",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Institution name"
            ),
        ),
    ]
