# Generated by Django 4.1.5 on 2023-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_ticket_locality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="locality",
            field=models.CharField(
                choices=[("online", "Online"), ("in-person", "In-person")],
                default="online",
                max_length=20,
            ),
        ),
    ]
