# Generated by Django 4.1.6 on 2023-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_participant_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
