# Generated by Django 4.2 on 2023-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_participant_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="title",
            field=models.CharField(
                choices=[
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Ms", "Ms"),
                    ("Miss", "Miss"),
                    ("Dr", "Dr"),
                    ("Prof", "Prof"),
                    ("Sir", "Sir"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
