# Generated by Django 4.1.5 on 2023-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_ticket_locality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=8, null=True
            ),
        ),
    ]
