# Generated by Django 4.2 on 2023-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_participant_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="order",
            name="kb_order_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Kapitalbank Ecommerce Order ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kb_session_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Kapitalbank Ecommerce Session ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("kb_order_id", "kb_session_id")},
        ),
        migrations.RemoveField(
            model_name="order",
            name="session_id",
        ),
    ]
