# Generated by Django 4.2 on 2023-04-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_kborder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paid_amount",
            new_name="amount",
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="order",
            name="kb_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="kb_session_id",
        ),
    ]
