# Generated by Django 4.2 on 2023-04-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_paid_amount_order_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
