# Generated by Django 4.2 on 2023-04-20 21:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=core.models.random_id, max_length=10, unique=True
            ),
        ),
    ]
