# Generated by Django 4.2 on 2023-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="kborder",
            name="url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
