# Generated by Django 4.2 on 2023-04-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_kborder_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kborder",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created",)},
        ),
    ]
