# Generated by Django 4.2 on 2023-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_kborder_options_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kborder",
            options={"ordering": ("created",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("created",)},
        ),
    ]
