"""
Django settings for cce_2023_registration project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_DIR = Path(__file__).resolve().parent
BASE_DIR = PROJECT_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&!$%afenbq^ehf0^e!r%!gm)!%!r%3p*vu8(a!2q8@ro145h19"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=list, default=[])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.forms",
    "django_extensions",
    "django_browser_reload",
    "phonenumber_field",
    "ckeditor",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "core",
    "solo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "cce_2023_registration.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [PROJECT_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cce_2023_registration.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# PAYRIFF configuration

PAYRIFF_BASE_URL = "https://api.payriff.com/api/v2"
PAYRIFF_CREATE_ORDER_URL = f"{PAYRIFF_BASE_URL}/createOrder"
PAYRIFF_REFUND_URL = f"{PAYRIFF_BASE_URL}/refund"
PAYRIFF_SECRET = config("PAYRIFF_SECRET")
PAYRIFF_MERCHANT_ID = config("PAYRIFF_MERCHANT_ID")
PAYRIFF_LANGUAGE = config("PAYRIFF_LANGUAGE", "EN")

PAYRIFF_APPROVE_URL = config(
    "PAYRIFF_APPROVE_URL", "http://localhost:8000/order-approved"
)
PAYRIFF_CANCEL_URL = config(
    "PAYRIFF_CANCEL_URL", "http://localhost:8000/order-canceled"
)
PAYRIFF_DECLINE_URL = config(
    "PAYRIFF_DECLINE_URL", "http://localhost:8000/order-declined"
)

PAYRIFF_CURRENCY = config("PAYRIFF_CURRENCY", "AZN")

PAYRIFF_ORDER_DESCRIPTION = config("ORDER_DESCRIPTION", default="CCE'23 Registration")
PAYRIFF_REQUEST_TIMEOUT = config("PAYRIFF_REQUEST_TIMEOUT", default=10)

# Phone-number-field settings
PHONENUMBER_DEFAULT_REGION = config("PHONENUMBER_DEFAULT_REGION", "AZ")

# Custom form renderer
FORM_RENDERER = "core.renderers.BootstrapFormRenderer"

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

LOGIN_REDIRECT_URL = "index"

SITE_ID = 1

# Django allauth configs
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SESSION_REMEMBER = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_FORMS = {
    "signup": "core.forms.SignupForm",
    "login": "core.forms.LoginForm",
    "reset_password": "core.forms.ResetPasswordForm",
    "reset_password_from_key": "core.forms.ResetPasswordKeyFrom",
    "set_password": "core.forms.SetPasswordForm",
    "change_password": "core.forms.ChangePasswordForm",
    "add_email": "core.forms.AddEmailForm",
}

# Email setup
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
DEFAULT_FROM_EMAIL = "g.rustamli@ufaz.az"

CONTACT_EMAIL = config("CONTACT_EMAIL")
CONTACT_PHONE = config("CONTACT_PHONE")

NOTICE_MESSAGE = "Due to technical issues we are not able to accept payments at the moment. You can register and " \
                 "order tickets now and pay later. We will inform you when the payment is available."
