version: "3.9"
services:
  web:
    build: .
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - /run/register.cce.ufaz.az.sock:/run/gunicorn.sock
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:15.2-alpine3.17
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
