version: "3.9"
services:
  web:
    build: .
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - /run/register.cce.ufaz.az.sock:/run/gunicorn.sock
    depends_on:
      - db
    restart: unless-stopped

