version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    env_file:
      - ../.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
